FROM python:3.10

# Install dependencies
COPY requirements_dev.txt .
RUN pip install --no-cache-dir -r requirements_dev.txt

RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    && rm -rf /var/lib/apt/lists/*